### ISSUE TITLE
Wrong text on scouting uninhabited island

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#2]
New Lands v0.3.1

![new_lands_uninhabited](https://user-images.githubusercontent.com/22425000/197162972-737d6a73-110d-4a85-99ec-627ed4b03e66.png)

This was caused perhaps by the combination of ship and island name because for all other uninhabited islands the text was displayed correctly.

**Comment by MagicKrol** [comment]
Fixed in 0.3.2
