### ISSUE TITLE
Wrong display of cannibal/pirate settlements

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#3]
New Lands v0.3.1

The status panel lists 10 cannibal and 0 pirate settlements while the detailed islands list has 8 cannibal and 2 pirates settlements.

Re-scouting Safe Bay after destroying its pirate hideout reports it as still having a hideout in the news (but not on the island list)

Destroying a cannibal village is sometimes reported in the news as a destroyed pirate hideout (and vice versa).

(Attached VICE 3.5 x64sc snapshot)

![new_lands_pirates_rescout](https://user-images.githubusercontent.com/22425000/197165356-c88b26a2-467a-46e6-b74f-8427c0cbe5d2.png)
[new_lands_pirates_rescout.zip](https://github.com/MagicKrol/C64-NewLands/files/9837769/new_lands_pirates_rescout.zip)

**Comment by MagicKrol** [comment]
Fixed in 0.4.1. Thanks :)
