### ISSUE TITLE
Garbled text on news

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#4]
New Lands v0.3.1

![new_lands_bad_ship](https://user-images.githubusercontent.com/22425000/197166033-503d4a5e-e911-43af-bfc8-9b9be123a6cd.png)
[new_lands_bad_ship.zip](https://github.com/MagicKrol/C64-NewLands/files/9837862/new_lands_bad_ship.zip)

I have attached three snapshots:

1: The initial state.
2: Moved the cursor down to 'next turn'. Hitting it produces the garbled text with good probabilty but not always.
3: The garbled text is displayed. Not just the ship name is wrong but also the class: it's not a pinnace but a galleon.

[ pinnace and galleon are misspelled as 'pinance' and 'galeon' in the game ]

**Comment by MagicKrol** [comment]
Hopefully fixed in 0.3.2 (it could happen if in the same turn ship is built and destroyed). 
And thanks for point out misspellings.
