### ISSUE TITLE
Reassigning repair to another port does not reset repair state

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#5]
New Lands v0.3.1

1. Sent Ga Maya to repair in San Marisa.
2. Changed my mind and sent it to repair to Macaria instead.

On entering the Macaria repair screen Maya is displayed as having 4/4 condition (despite it being only 3/4) and the wood for the repair is taken from San Marisa inventory not Macaria.

[new_lands_repair_wood.zip](https://github.com/MagicKrol/C64-NewLands/files/9838008/new_lands_repair_wood.zip)
![new_lands_repair_wood](https://user-images.githubusercontent.com/22425000/197170726-4745f75f-7acd-4b26-a37f-0da00173acf5.png)

**Comment by MagicKrol** [comment]
Fixed in 0.3.2
