### ISSUE TITLE
Conquest victory condition does not trigger

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#6]
New Lands v0.3.1

I have destroyed all pirate and cannibal settlements yet no victory is reported.
[new_lands_shouldhavewon.zip](https://github.com/MagicKrol/C64-NewLands/files/9842830/new_lands_shouldhavewon.zip)

May be linked to issue #3

**Comment by MagicKrol** [comment]
Fixed in 0.3.2
