### ISSUE TITLE
Colony is not shown on islands list

### ISSUE THREAD

**Issue by dabadab** [MagicKrol/C64-NewLands#7]
New Lands v0.4

Colony Liberte is on Safe Haven yet the 'View Island' shows Safe Haven as uninhabited.

[new_lands_lost_colony.zip](https://github.com/MagicKrol/C64-NewLands/files/9905447/new_lands_lost_colony.zip)

**Comment by maciej-krol** [comment]
Fixed 0.4.1

**Comment by MagicKrol** [comment]
Fixed in 0.4.1. Thanks
